// LG 제품 이미지 임포트
import lgBuds from '../../assets/shop/buds.webp';
import lgCleaner from '../../assets/shop/cleaner.jpg';
import lgConditioner from '../../assets/shop/conditioner.jpg';
import lgFootClean from '../../assets/shop/footclean.jpg';
import lgHandCream from '../../assets/shop/handcream.jpg';

// 기프티콘 데이터 (구체적인 제품)
export const GIFTICONS = [
    {
        id: 1,
        name: '아메리카노 (Tall)',
        brand: '스타벅스',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400',
        price: 4500,
        popular: false,
    },
    {
        id: 2,
        name: '카페라떼 (Grande)',
        brand: '스타벅스',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?w=400',
        price: 5500,
        popular: false,
    },
    {
        id: 3,
        name: '아메리카노 (Large)',
        brand: '이디야커피',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=400',
        price: 3000,
        popular: false,
    },
    {
        id: 4,
        name: '카페라떼',
        brand: '이디야커피',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400',
        price: 3500,
        popular: false,
    },
    {
        id: 5,
        name: '케이크 세트',
        brand: '투썸플레이스',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
        price: 8000,
        popular: false,
    },
    {
        id: 6,
        name: '아메리카노 (Mega)',
        brand: '메가커피',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400',
        price: 2000,
        popular: false,
    },
    {
        id: 7,
        name: '달콤 아이스크림',
        brand: '빽다방',
        category: 'cafe',
        image: 'https://images.unsplash.com/photo-1497534446932-c925b458314e?w=400',
        price: 3500,
        popular: false,
    },
    {
        id: 8,
        name: '삼각김밥 2개 + 음료',
        brand: 'GS25',
        category: 'convenience',
        image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=400',
        price: 4500,
        popular: false,
    },
    {
        id: 9,
        name: '도시락 + 음료',
        brand: 'GS25',
        category: 'convenience',
        image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
        price: 6500,
        popular: false,
    },
    {
        id: 10,
        name: '컵라면 + 주먹밥',
        brand: 'CU',
        category: 'convenience',
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400',
        price: 3500,
        popular: false,
    },

    {
        id: 12,
        name: '삼각김밥 3개',
        brand: '세븐일레븐',
        category: 'convenience',
        image: 'https://images.unsplash.com/photo-1601599561213-832382fd07ba?w=400',
        price: 3900,
        popular: false,
    },
    {
        id: 13,
        name: '빅맥 세트',
        brand: '맥도날드',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1619454016518-697bc231e7cb?w=400',
        price: 6500,
        popular: false,
    },
    {
        id: 14,
        name: '맥너겟 6조각',
        brand: '맥도날드',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=400',
        price: 4500,
        popular: false,
    },
    {
        id: 15,
        name: '와퍼 세트',
        brand: '버거킹',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400',
        price: 6900,
        popular: false,
    },
    {
        id: 16,
        name: '치킨버거 세트',
        brand: '버거킹',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400',
        price: 5500,
        popular: false,
    },
    {
        id: 17,
        name: '오리지널 치킨 6조각',
        brand: 'KFC',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400',
        price: 8500,
        popular: false,
    },
    {
        id: 18,
        name: '징거버거 세트',
        brand: 'KFC',
        category: 'restaurant',
        image: 'https://images.unsplash.com/photo-1513185158878-8d8c2a2a3da3?w=400',
        price: 6500,
        popular: false,
    },
    {
        id: 19,
        name: '베스트셀러 도서',
        brand: '교보문고',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400',
        price: 15000,
        popular: false,
    },
    {
        id: 20,
        name: '문구/잡화 상품권',
        brand: '교보문고',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
        price: 10000,
        popular: false,
    },
    {
        id: 21,
        name: '영화 관람권 (1인)',
        brand: 'CGV',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
        price: 13000,
        popular: false,
    },
    {
        id: 22,
        name: '팝콘 콤보',
        brand: 'CGV',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?w=400',
        price: 8000,
        popular: false,
    },
    {
        id: 23,
        name: '무신사 10,000원 쿠폰',
        brand: '무신사',
        category: 'fashion',
        image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400',
        price: 10000,
        popular: false,
    },
    {
        id: 24,
        name: '무신사 30,000원 쿠폰',
        brand: '무신사',
        category: 'fashion',
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400',
        price: 30000,
        popular: false,
    },
    {
        id: 25,
        name: '쿠팡 로켓배송 쿠폰',
        brand: '쿠팡',
        category: 'shopping',
        image: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=400',
        price: 5000,
        popular: false,
    },
    {
        id: 26,
        name: '쿠팡 생활용품 쿠폰',
        brand: '쿠팡',
        category: 'shopping',
        image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400',
        price: 10000,
        popular: false,
    },
    // LG 제품들
    {
        id: 11,
        name: 'LG 톤프리 무선 이어버드',
        brand: 'LG전자',
        category: 'electronics',
        image: lgBuds,
        price: 89000,
        popular: true,
    },
    {
        id: 27,
        name: '다목적 세정제 라벤더',
        brand: '미세스마이어스',
        category: 'beauty',
        image: lgCleaner,
        price: 10000,
        popular: true,
    },
    {
        id: 28,
        name: '딥모이처 컨디셔너',
        brand: '엘라스틴',
        category: 'beauty',
        image: lgConditioner,
        price: 12000,
        popular: true,
    },
    {
        id: 29,
        name: '발을 씻자',
        brand: '온더바디',
        category: 'beauty',
        image: lgFootClean,
        price: 6000,
        popular: true,
    },
    {
        id: 30,
        name: 'LG 뷰티 핸드크림 세트',
        brand: 'LG생활건강',
        category: 'beauty',
        image: lgHandCream,
        price: 15000,
        popular: true,
    },
];

// 카테고리 정의
export const CATEGORIES = [
    { id: 'all', label: '전체', icon: '🎁' },
    { id: 'electronics', label: 'LG전자', icon: '⚡' },
    { id: 'beauty', label: '뷰티/생활', icon: '💄' },
    { id: 'cafe', label: '카페/음료', icon: '☕' },
    { id: 'restaurant', label: '외식', icon: '🍔' },
    { id: 'convenience', label: '편의점', icon: '🏪' },
    { id: 'culture', label: '문화', icon: '🎬' },
    { id: 'fashion', label: '패션', icon: '👕' },
    { id: 'shopping', label: '쇼핑', icon: '🛒' },
];

// 정렬 옵션
export const SORT_OPTIONS = [
    { id: 'popular', label: '인기순' },
    { id: 'low', label: '낮은 포인트순' },
    { id: 'high', label: '높은 포인트순' },
];

// 교환 내역 샘플 데이터
export const EXCHANGE_HISTORY = [
    {
        id: 1,
        type: 'gifticon',
        name: '아메리카노 (Tall)',
        brand: '스타벅스',
        points: 4500,
        date: '2025-11-03',
        status: 'completed',
    },
    {
        id: 2,
        type: 'transfer',
        name: '계좌이체',
        brand: '계좌이체',
        points: 10000,
        date: '2025-11-02',
        status: 'processing',
    },
    {
        id: 3,
        type: 'gifticon',
        name: '삼각김밥 2개 + 음료',
        brand: 'GS25',
        points: 4500,
        date: '2025-11-01',
        status: 'completed',
    },
    {
        id: 4,
        type: 'gifticon',
        name: '영화 관람권 (1인)',
        brand: 'CGV',
        points: 13000,
        date: '2025-10-30',
        status: 'completed',
    },
    {
        id: 5,
        type: 'transfer',
        name: '계좌이체',
        brand: '계좌이체',
        points: 5000,
        date: '2025-10-28',
        status: 'completed',
    },
    {
        id: 6,
        type: 'gifticon',
        name: '쿠팡 로켓배송 쿠폰',
        brand: '쿠팡',
        points: 5000,
        date: '2025-10-25',
        status: 'completed',
    },
    {
        id: 7,
        type: 'gifticon',
        name: '빅맥 세트',
        brand: '맥도날드',
        points: 6500,
        date: '2025-10-20',
        status: 'pending',
    },
];
